name: PHPUnit

on:
  pull_request:
  push:
    branches: [ main, master, develop ]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    name: php${{ matrix.php-versions }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: gd
          coverage: none

      - name: Set up PHP dependencies
        run: composer i

      - name: PHPUnit
        run: ./vendor/bin/phpunit
