nameOverride: "easyappointments"
fullnameOverride: "easyappointments"

replicaCount: 1

image:
  repository: jamrizzi/easyappointments
  pullPolicy: IfNotPresent
  tag: latest
imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
app:
  Port: 8888
  envVars:
    BASE_URL: http://localhost:8888
    LANGUAGE: russian
    PHP_DEBUG_MODE: true
    GOOGLE_SYNC_FEATURE: false
    GOOGLE_PRODUCT_NAME: ''
    GOOGLE_CLIENT_ID: ''
    GOOGLE_CLIENT_SECRET: ''
    GOOGLE_API_KEY: ''

dataBase:
  databaseHost: my-release-mysql
  dbUser: root
  dbUserPassword: 11vy2vJrko
  dbName: easyappointmentsDB

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
